name: Build template

trigger:
  - master
pr:
  branches:
    include:
    - '*'

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: .ci/utils/use-node.yml
      - template: .ci/utils/use-esy.yml
      - script: mkdir $(Pipeline.Workspace)/hello-reason
        displayName: "Create project folder"
      - script: "pesy --template=esy/pesy-reason-template#$(Build.SourceBranchName)"
        displayName: "Initialize pesy template"
        workingDirectory: $(Pipeline.Workspace)/hello-reason
      - script: "esy test"
        displayName: "Run tests"
        workingDirectory: $(Pipeline.Workspace)/hello-reason

  - job: macOS
    pool:
      vmImage: macOS-latest
    steps:
      - template: .ci/utils/use-node.yml
      - template: .ci/utils/use-esy.yml
      - script: mkdir $(Pipeline.Workspace)/hello-reason
        displayName: "Create project folder"
      - script: "pesy --template=esy/pesy-reason-template#$(Build.SourceBranchName)"
        displayName: "Initialize pesy template"
        workingDirectory: $(Pipeline.Workspace)/hello-reason
      - script: "esy test"
        displayName: "Run tests"
        workingDirectory: $(Pipeline.Workspace)/hello-reason
  
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
      - template: .ci/utils/use-node.yml
      - template: .ci/utils/use-esy.yml
      - script: "npm install -g pesy@next"
        displayName: "install pesy"
      - script: mkdir $(Pipeline.Workspace)/hello-reason
        displayName: "Create project folder"
      - script: "pesy --template=esy/pesy-reason-template#$(Build.SourceBranchName)"
        displayName: "Initialize pesy template"
        workingDirectory: $(Pipeline.Workspace)/hello-reason
      - script: "esy test"
        displayName: "Run tests"
        workingDirectory: $(Pipeline.Workspace)/hello-reason
